const std = @import("std");
const g = @import("geometry.zig");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: obj2zig <input_path> <output_path>\n", .{});
        std.process.exit(1);
    }

    const input_path = args[1];
    const output_path = args[2];

    const input = try std.fs.cwd().openFile(input_path, .{});
    defer input.close();

    var faces = std.ArrayList(g.Face).empty;
    defer faces.deinit(allocator);

    var vertices = std.ArrayList(g.V3f).empty;
    defer vertices.deinit(allocator);

    var texcoords = std.ArrayList(g.V2f).empty;
    defer texcoords.deinit(allocator);

    const read_buf = try allocator.alloc(u8, 1024);
    defer allocator.free(read_buf);

    var file_reader = input.reader(read_buf);
    var reader = &file_reader.interface;

    while (try reader.takeDelimiter('\n')) |line| {
        if (line.len == 0) continue;
        var parts = std.mem.splitScalar(u8, line, ' ');
        const indicator = parts.next().?;
        if (std.mem.eql(u8, indicator, "v")) {
            var x = try std.fmt.parseFloat(f32, parts.next().?);
            var y = try std.fmt.parseFloat(f32, parts.next().?);
            var z = try std.fmt.parseFloat(f32, parts.next().?);

            if (z == -0.0) z = 0.0;
            if (y == -0.0) y = 0.0;
            if (x == -0.0) x = 0.0;

            try vertices.append(allocator, g.V3f{ .x = x, .y = y, .z = z });
        } else if (std.mem.eql(u8, indicator, "vt")) {
            const u = try std.fmt.parseFloat(f32, parts.next().?);
            const v = try std.fmt.parseFloat(f32, parts.next().?);

            try texcoords.append(allocator, g.V2f{ .x = u, .y = v });
        } else if (std.mem.eql(u8, indicator, "f")) {
            var vertex_indices: [4]u32 = undefined;
            var texcoord_indices: [4]u32 = undefined;
            var vertex_count: usize = 0;
            var has_texcoords = false;

            while (parts.next()) |face_part| {
                if (vertex_count >= 4) break; // Only support triangles and quads
                var face_iter = std.mem.splitScalar(u8, face_part, '/');
                const vertex_index = try std.fmt.parseInt(u32, face_iter.next().?, 10) - 1;
                vertex_indices[vertex_count] = vertex_index;
                vertex_count += 1;

                if (face_iter.next()) |texcoord_part| {
                    const texcoord_index = try std.fmt.parseInt(u32, texcoord_part, 10) - 1;
                    texcoord_indices[vertex_count - 1] = texcoord_index;
                    has_texcoords = true;
                }
            }

            if (vertex_count == 3) {
                // Triangle: v0, v1, v2
                var face = g.Face{
                    .vertex_indices = .{ vertex_indices[0], vertex_indices[1], vertex_indices[2] },
                };
                if (has_texcoords) {
                    face.texcoord_indices = .{ texcoord_indices[0], texcoord_indices[1], texcoord_indices[2] };
                }
                try faces.append(allocator, face);
            } else if (vertex_count == 4) {
                // Quad: split into two triangles (v0, v1, v2) and (v0, v2, v3)
                var face1 = g.Face{
                    .vertex_indices = .{ vertex_indices[0], vertex_indices[1], vertex_indices[2] },
                };
                var face2 = g.Face{
                    .vertex_indices = .{ vertex_indices[0], vertex_indices[2], vertex_indices[3] },
                };

                if (has_texcoords) {
                    face1.texcoord_indices = .{ texcoord_indices[0], texcoord_indices[1], texcoord_indices[2] };
                    face2.texcoord_indices = .{ texcoord_indices[0], texcoord_indices[2], texcoord_indices[3] };
                }
                try faces.append(allocator, face1);
                try faces.append(allocator, face2);
            }
        }
    }

    if (std.fs.path.dirname(output_path)) |dir_path| {
        std.fs.cwd().makePath(dir_path) catch {};
    }

    const output = try std.fs.cwd().createFile(output_path, .{});
    defer output.close();

    const write_buf = try allocator.alloc(u8, 65536);
    defer allocator.free(write_buf);
    var file_writer = output.writer(write_buf);

    var writer = &file_writer.interface;

    try writer.print("// This file is autogenerated by obj2zig.zig\n", .{});
    try writer.print("const g = @import(\"geometry\");\n\n", .{});
    try writer.print("pub const vertices = [_]g.V3f{{\n", .{});
    for (vertices.items) |v| {
        try writer.print("    .{{ .x = {}, .y = {}, .z = {} }},\n", .{ v.x, v.y, v.z });
    }
    try writer.print("}};\n\n", .{});

    try writer.print("pub const texcoords = [_]g.V2f{{\n", .{});
    if (texcoords.items.len > 0) {
        for (texcoords.items) |t| {
            try writer.print("    .{{ .x = {}, .y = {} }},\n", .{ t.x, t.y });
        }
    }
    try writer.print("}};\n\n", .{});

    try writer.print("pub const faces = [_]g.Face{{\n", .{});
    for (faces.items) |f| {
        const v = f.vertex_indices;
        try writer.print("    .{{ .vertex_indices = .{{ {}, {}, {} }}", .{ v[0], v[1], v[2] });
        if (f.texcoord_indices) |t| {
            try writer.print(", .texcoord_indices = .{{ {}, {}, {} }}", .{ t[0], t[1], t[2] });
        }
        try writer.print(" }},\n", .{});
    }
    try writer.print("}};\n", .{});

    try writer.flush();
}
